name: First Workflow

on: push

jobs:
  build: 
    runs-on : ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run a simple github action
      run: echo "this workflow run successfully for this action"

    - name: $imulating Error
      run: echo "error taking place"; exit 1 
      
    - id: nodenv
      uses: nodenv/actions/node-version@v3
    - run: echo ${{ steps.nodenv.outputs.node-version }}
